### ISSUE TITLE
Accept IPV4 addresses

### ISSUE THREAD

**Issue by ivandardi** [SirRade/slowloris-rs#1]
Hello.

I'd like to test a slowloris attack that's on my local network. And for that I'd need to use its direct IPv4 address instead of an URL. However, when I try I get

```
C:\Users\user>slowloris 172.21.23.71:2000
Preparing connections...
thread 'main' panicked at 'Error while attacking: UrlParseError(RelativeUrlWithoutBase)', src\libcore\result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Can this feature please be implemented?

**Comment by janhohenheim** [comment]
Sure, I can take a look at it later.

**Comment by janhohenheim** [comment]
I think I solved your problem. Feel free to reopen this issue if it doesn't work.
You can apply the update by running the following command:
```sh
 cargo install --force slowloris
```

**Comment by ivandardi** [comment]
Awesome! I'll test it out next Thursday. Thanks! 😄
